'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
'''

def even_fibonacci_sum(n: int) -> int:
    prev = 1
    curr = 1
    even_sum = 0
    while curr <= n:
        nxt = prev + curr
        if nxt % 2 == 0:
            even_sum += nxt
        prev = curr
        curr = nxt
    return even_sum

if __name__ == '__main__':
    print(even_fibonacci_sum(4000000))
